
[[pages]]
path = "app_pages/engagement.py"
name = "Curious Learning Dashboard"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/single_funnel.py"
name = "App Funnel"
icon = ":small_orange_diamond:"

